name: live
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
#  flutter_azure_tts: ^0.1.6
  audioplayers: ^6.1.0
  keep_screen_on: ^3.0.0
  media_cache_manager: ^0.2.1
  better_player: ^0.0.83
  video_player: ^2.7.0
  dio:
  internet_connection_checker:
  fluttertoast: ^8.2.1
  dartz:
  pretty_dio_logger: ^1.3.1
  shared_preferences:
  get_it:
  volume_controller: ^2.0.8
  http:
  provider:
#  flutter_staggered_animations:
#  connectivity:
  connectivity_plus:
  image_picker:
  cached_network_image:
#  flutter_styled_toast:
#  flutter_animated_dialog:
  loading_animation_widget: ^1.2.0+4
  flutter_animate:
  url_launcher: ^6.1.11
#  readmore:
  flutter_svg:
  flutter_local_notifications:
  flutter_form_builder:
  flutter_launcher_icons: ^0.14.1
  equatable:
  pin_code_fields:
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^3.0.0-pre
#  rxdart:
  restart_app: ^1.2.1
#  shimmer:
  carousel_slider: ^5.0.0
  whatsapp_unilink: ^2.1.0

  text_scroll: ^0.2.0
  signalr_core:
  flutter_native_splash: ^2.2.0+1
  code_scan_listener: ^0.4.1
  syncfusion_flutter_charts: ^27.1.52
  flutter_typeahead:
#  geolocator_platform_interface:
#  geolocator:
#  geolocator:
#  google_maps_flutter:
#  map_launcher:
  flutter_polyline_points:
  country_picker: ^2.0.20
  flag:
  flutter_spinkit:
  app_settings:
  substring_highlight: ^1.0.33
  motion_toast: ^2.6.8
#  flutter_tts: ^4.0.2
  flutter_tts: ^3.8.1

#  flutter_inappwebview: ^6.1.5



dev_dependencies:
  intl: 0.19.0
  flutter_launcher_icons: ^0.14.1


  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "flutter_luancher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/en/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/en/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/en/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Light.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/en/Roboto-Black.ttf
          weight: 800

    - family: ar
      fonts:
        - asset: assets/fonts/ar/ExpoArabic-regular.ttf
          weight: 400
        - asset: assets/fonts/ar/ExpoArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Expo Arabic SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Expo Arabic Bold.ttf
          weight: 700


          # scanner barcode
          # remote device
          # keyboard
          # the sound doesnt work and have
          # delay in 2 orders in same time